from flask_wtf import Form 
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Email, Length

class adminForm(Form):
	username = StringField('Username', [DataRequired('What is your username ? '),
	Length(min=4)
])
	pwdhash = PasswordField('Password', validators = [DataRequired()])
	submit = SubmitField('Submit')


class blogForm(Form):
	main_topic = StringField('Main Topic', [DataRequired()])

	topic_expl = TextAreaField('Topic Explanation', [DataRequired()])
	blog_topic = StringField('Blog Topic', [DataRequired()])
	body = TextAreaField('Body 1')
	highlight = TextAreaField('Highlight')
	body2 = TextAreaField('Body 2')
	author_name = StringField('Author Name', [DataRequired()])
	author_expl = TextAreaField('Author Explanation')
	key_words = StringField('Key Words')


	submit = SubmitField('Submit')
	update = SubmitField('Update')
	
	
class servicesForm(Form):

	guide = TextAreaField('Guide')
	hotel = TextAreaField('Hotel Reservation')
	transportation = TextAreaField('Transportation')
	insurance = TextAreaField('Insurance')
	flight = TextAreaField('Flight')
	visa = TextAreaField('Visa')

	submit = SubmitField('Submit')
	update = SubmitField('Update')
	
	
class toursForm(Form):

	paragraph_title = StringField('Paragraph Title')
	paragraph = TextAreaField('Paragraph')
	submit = SubmitField('Submit')
	update = SubmitField('Update')
	
	
class homeForm(Form):
	slide1_place = StringField('slide1_place')
	slide1_discover = StringField('slide1_discover ')
	slide1_title = StringField('slide1_title')
	slide1_text =  TextAreaField('slide1_text')
	slide2_place = StringField('slide2_place')
	slide2_discover = StringField('slide2_discover')
	slide2_title = StringField('slide2_title')
	slide2_text = TextAreaField('slide2_text')
	slide3_place = StringField('slide3_place')
	slide3_discover = StringField('slide3_discover ')
	slide3_title = StringField('slide3_title')
	slide3_text = TextAreaField('slide3_text')
	plan_motto = StringField('plan_motto')
	plan_title = StringField('plan_title')
	plan_expl = TextAreaField('plan_expl')
	travel_motto = StringField('travel_motto')
	travel_title = StringField('travel_title')
	travel_expl = TextAreaField('travel_expl')
	travel_city1 = StringField('travel_city1')
	travel_place1 = StringField('travel_place1')
	travel_expl1 = TextAreaField('travel_expl1')
	travel_city2 = StringField('travel_city2')
	travel_place2 = StringField('travel_place2')
	travel_expl2 = 	TextAreaField('travel_expl2')
	travel_city3 = StringField('travel_city3')
	travel_place3 = StringField('travel_place3')
	travel_expl3 = 	TextAreaField('travel_expl3')
	travel_city4 = StringField('travel_city4')
	travel_place4 = StringField('travel_place4')
	travel_expl4 = TextAreaField('travel_expl4')
	travel_city5 = StringField('travel_city5')
	travel_place5 = StringField('travel_place5')
	travel_expl5 = 	TextAreaField('travel_expl5')
	travel_city6 = StringField('travel_city6')
	travel_place6 = StringField('travel_place6')
	travel_expl6 = 	TextAreaField('travel_expl6')
	service_motto = StringField('service_motto')
	service_title = StringField('service_title')
	service_expl = TextAreaField('service_expl')
	service_title1 = StringField('service_title1')
	service_expl1 = TextAreaField('service_expl1')
	service_title2 = StringField('service_title2 ')
	service_expl2 = TextAreaField('service_expl2')
	service_title3 = StringField('service_title3')
	service_expl3 = TextAreaField('service_expl3')
	service_title4 = StringField('service_title4')
	service_expl4 = TextAreaField('service_expl4')
	testimonia1_motto = StringField('testimonial_motto')
	testimonia1_title = StringField('testimonial_title')
	testimonia1_expl1 = TextAreaField('testimonial_expl1')
	testimonia1_name1 = StringField('testimonial_name1')
	testimonia1_position1 = StringField('testimonial_position1')
	testimonia1_expl2 = TextAreaField('testimonial_expl2')
	testimonia1_name2 = StringField('testimonial_name2')
	testimonia1_position2 = StringField('testimonial_position2')
	testimonia1_expl3 = TextAreaField('testimonial_expl3')
	testimonia1_name3 = StringField('testimonial_name3')
	testimonia1_position3 = StringField('testimonial_position3')
	testimonia1_expl4 = TextAreaField('testimonial_expl4')
	testimonia1_name4 = StringField('testimonial_name4')
	testimonia1_position4 = StringField('testimonial_position4')
	testimonia1_expl5 = TextAreaField('testimonial_expl5')
	testimonia1_name5 = StringField('testimonial_name5')
	testimonia1_position5 = StringField('testimonial_position5')
	route_motto = StringField('route_motto')
	route_title = StringField('route_expl')
	route_expl = TextAreaField('route_expl')
	route_city1 = StringField('route_city1')
	route_place1 = StringField('route_place1')
	route_expl1 = TextAreaField('route_expl1')
	route_city2 = StringField('route_city2')
	route_place2 = StringField('route_place2')
	route_expl2 = TextAreaField('route_expl2')
	route_city3 = StringField('route_city3')
	route_place3 = StringField('route_place3')
	route_expl3 = TextAreaField('route_expl3')
	blog_motto = StringField('slide1_place')
	blog_title = StringField('blog_motto')
	blog_expl = TextAreaField('blog_expl')
	about_motto = StringField('about_motto')
	about_title = StringField('about_title')
	about_expl = TextAreaField('about_expl')
	about_main_title = StringField('about_main_title')
	about_main = TextAreaField('about_main')
	submit = SubmitField('Submit')
	update = SubmitField('Update')
